### ISSUE TITLE
Deleting files in Store Browser

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#31]
I tried to delete an uploaded file (document/2). Didn't work - file is still there.

**Comment by asimshah** [comment]
Fixed in the next version

**Comment by asimshah** [comment]
Test is now upgraded

**Comment by asimshah** [comment]
please test this and close if possible

**Comment by mikebattye** [comment]
This still does not work on dwh.test. Uploaded an image but it remains in store after deletion.

**Comment by asimshah** [comment]
you should be using dwhnew.test

**Comment by asimshah** [comment]
actually your original issue said that a document could not be deleted and that is what I have looked at. I'll check what is happening with images - but please check if documents are deleted properly or not.

**Comment by mikebattye** [comment]
I have checked this carefully. An existing or newly uploaded document is successfully deleted, However an **image** file remains in the store even after the confirm deletion dialog box.
